name: Deploy

on:
  push:
    branches: master
    paths:
      - claim-gui/**
      - tooling/_harvest/checkpoints/**

defaults:
  run:
    working-directory: ./claim-gui

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_INFURA_KEY: ${{ secrets.INFURA_API_KEY  }}
      REACT_APP_WALLET_CONNECT_ID: ${{ secrets.WALLET_CONNECT_ID }}
    name: deploy claim-gui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "claim-gui/yarn.lock"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./claim-gui/build
