name: Harvest

on:
  schedule:
    - cron: "0 11 * * *"

defaults:
  run:
    working-directory: ./tooling

jobs:
  harvest-schedule:
    runs-on: ubuntu-latest
    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY  }}
    name: schedule harvest
    steps:
      - uses: actions/checkout@main
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "tooling/yarn.lock"
      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn compile
      - run: yarn hardhat harvest
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated Message: Update Schedule & Allocations"
          branch: master
          commit_user_name: Guild Bot
          commit_user_email: automation@gnosisguild.org
          commit_author: Guild Bot <automation@gnosisguild.org>
