name: Validate

on:
  push:
    branches: master

defaults:
  run:
    working-directory: ./tooling

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY  }}
    name: schedule:validate
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "tooling/yarn.lock"
      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn compile
      - run: yarn hardhat schedule:validate --deep true
      - run: yarn hardhat audit
